SAAS-Milestone-09/college_portal/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root :to=>"static_pages#index"
	resources :departments, only: [:index, :create, :new]
	resources :sections, only: [:index, :new, :create]
	resources :students, only: [:index, :new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

SAAS-Milestone-09/college_portal/app/models/department.rb
class Department < ApplicationRecord
	#associations
	has_many :students, :through => :sections
	has_many :sections,:dependent => :destroy
	#validations
	validates :name, presence: true, uniqueness: true
	#callbacks
	before_create :change_to_capital

	private
	def change_to_capital
		self.name = self.name.upcase
	end
end

SAAS-Milestone-09/college_portal/app/models/section.rb
class Section < ApplicationRecord
	 #associations
	 belongs_to :department
	 has_many :students , :dependent => :destroy
	 #callbacks
	 before_create :change_to_capital

	 private
	 def change_to_capital
	 	self.name = self.name.upcase
	 end
end

SAAS-Milestone-09/college_portal/app/models/student.rb
class Student < ApplicationRecord
	#associations
	belongs_to :section
	belongs_to :department
	
	#validations
	validates :email, uniqueness: true
	validates :name, :presence => true
	validates :section_id, :presence=>true
	validates :department_id, :presence=>true

	validate :validate_section_mapping
	
	#callbacks
  	before_create :generate_roll_no

 	private

 	def validate_section_mapping
    		section = Section.find_by_id(section_id)
		if section
    			if section.department_id!=department_id
      				errors.add(:section, "Selected section doesn't belongs to selected department")
    			end
		end
  	end
	
	def generate_roll_no
    		max_count = Student.count
    		department_name = department.name.downcase.gsub(/\s/, '-')
    		section_name = section.name.downcase.gsub(/\s/, '-')
    		self.roll_no = "#{department_name}-#{section_name}-#{max_count+1}"
  	end
end

SAAS-Milestone-09/college_portal/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

SAAS-Milestone-09/college_portal/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

SAAS-Milestone-09/college_portal/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  def index
    @departments = Department.all
  end

  def new
     unless current_user.admin?
    	flash[:danger] = "You are not allowed to access this page."
    	redirect_to root_path
     end

     @department = Department.new
  end


  def create
  	unless current_user.admin?
    		flash[:danger] = "You are not allowed to access this page."
    		redirect_to root_path
  	end

  	@department = Department.new(department_params)

  	if @department.save
    		redirect_to action: "index"
  	else
    		flash[:danger] = @department.errors.values.join(', ')
    		redirect_to action: "new"
  	end
   end

   private
   def department_params
    params[:department].permit(:name)
   end
end

SAAS-Milestone-09/college_portal/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :authenticate_user!
  def index
    if params[:department_id]
      @sections = Section.where(department_id: params[:department_id]).all
    else
      @sections = Section.all
    end
  end

  def new
    unless current_user.admin?
    	flash[:danger] = "You are not allowed to access this page."
    	redirect_to root_path
    end

    @section = Section.new
    @department_collection = Department.all.collect { |p| [p.name, p.id] }
  end

  def create

    unless current_user.admin?
    	flash[:danger] = "You are not allowed to access this page."
    	redirect_to root_path
    end

    @section = Section.new(section_params)
    if @section.save
      redirect_to action: "index"
    else
      render "new"
    end
  end

  private

  def section_params
    params[:section].permit(:name, :department_id)
  end
end

SAAS-Milestone-09/college_portal/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def index	
	end
end

SAAS-Milestone-09/college_portal/app/controllers/students_controller.rb
class StudentsController < ApplicationController
	before_action :authenticate_user!
	def index
	    if params[:department_id]&&params[:section_id]
	      @students = Student.where({department_id: params[:department_id],section_id: params[:section_id]}).all
	    elsif params[:department_id]
			@students = Student.where(department_id: params[:department_id]).all
	    elsif params[:section_id]
			@students = Student.where(section_id: params[:section_id]).all
	    else 	
	      @students = Student.all
	    end
	end

	  def new
	    
	    unless current_user.admin?
    		flash[:danger] = "You are not allowed to access this page."
    		redirect_to root_path
     	    end

	    @student = Student.new
	    @section_collection = Section.all.collect { |p| [p.name, p.id]}
	    @department_collection = Department.all.collect { |p| [p.name, p.id] }
	  end

	  def create
	    
	    unless current_user.admin?
    		flash[:danger] = "You are not allowed to access this page."
    		redirect_to root_path
  	    end
	    
	    @student = Student.new(student_params)
	    if @student.save
	      	redirect_to action: "index"
	    else
	      	flash[:danger] = @student.errors.values.join(', ')
    		redirect_to action: "new"
	    end
	  end

	  def show
	    @students = Student.find(params[:id])
	    @sections = Section.find(@students.section_id)
	    @departments = Department.find(@students.department_id)	
	  end

	  private

	  def student_params
	    params[:student].permit(:name, :section_id, :department_id, :student_id, :email, :roll_no)
	  end
end

SAAS-Milestone-09/college_portal/app/helpers/departments_helper.rb
module DepartmentsHelper
end

SAAS-Milestone-09/college_portal/app/helpers/sections_helper.rb
module SectionsHelper
end

SAAS-Milestone-09/college_portal/app/helpers/students_helper.rb
module StudentsHelper
end

SAAS-Milestone-09/college_portal/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Students Portal</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=root_path%>">College Portal</a>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="<%=departments_path%>">Departments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=sections_path%>">Sections</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=students_path%>">Students</a>
        </li>
      <% end %>
    </ul>
  </div>

  <span class="navbar-text text-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong> |
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </span>
</nav>

<div class="container">
  <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
    <% elsif alert %>
  <p class="alert alert-danger"><%= alert %></p>
  <% else %>
    <% flash.each do |key, value| %>
      <%= content_tag(:p, value, class: "alert alert-#{key}") %>
    <% end %>
  <% end %>


  <%= yield %>
</div>

<footer class="page-footer font-small bg-dark">
  <div class="footer-copyright text-center py-3 text-light">(c) 2019 Freshworks:
    <a href="https://freshworks.com"> freshworks.com</a>
  </div>
</footer>
</body>
</html>

SAAS-Milestone-09/college_portal/app/views/sections/index.html.erb
<br>
<div class="row">
  <div class="col-md-10">
    <h2>Sections</h2>
  </div>
  <% if current_user.admin? %>
  	<div class="col-md-2">
    		<a class="btn btn-primary float-right" href="<%= new_section_path %>" role="button">Create</a>
  	</div>
  <% end %>
</div>
<br/>
<ul class="list-group">
  <% @sections.each do |section| %>
    <li class="list-group-item">
	<a href="<%= students_path(section_id: section.id) %>">
		<%= section.name %>
	</a>
    </li>
  <% end %>
</ul>

SAAS-Milestone-09/college_portal/app/views/sections/new.html.erb
<h2>Create Section</h2>

<%= form_for(@section) do |f| %>
  <div class="form-group">
    <label>Name</label>
    <%= f.text_field :name, class: "form-control", placeholder: "Section Name", required: true%>
    <br/>
    <label>Department</label>
    <%= f.select :department_id, @department_collection, { prompt: 'Select Department' }, class: "form-control", required: true%>
    <br/>
    <%= f.submit text: "create", class: "btn btn-primary"%>
  </div>
<% end %>