final_project/config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'
  get 'twitter/index'
  get 'github/index'
  get 'contacts/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root :to=> "static_pages#index"
resources :github, only: [:index]
resources :twitter, only: [:index]
resources :contacts, only: [:index,:create]
end

final_project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

final_project/app/models/contact.rb
class Contact < ApplicationRecord
end

final_project/app/models/repository.rb
class Repository < ApplicationRecord
end

final_project/app/models/tweet.rb
class Tweet < ApplicationRecord
end

final_project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

final_project/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
    		@contact = Contact.new
  	end

	def create
	    @contact= Contact.new(contact_params)
  	#	respond_to do |format|
    	if @contact.save
      # Sends email to user when user is created.
      	ExampleMailer.sample_email(@contact).deliver
    #  	format.html { redirect_to @contact, notice: 'User was successfully created.' }
    #  	format.json { render :show, status: :created, location: @contact }
    else
    #  	format.html { render :new }
    #  	format.json { render json: @contact.errors, status: :unprocessable_entity }
    #end
  end
	  redirect_to :controller => 'static_pages', :action => 'index'
end
	private

  	def contact_params
    		params[:contact].permit(:name, :email, :feedback)
  	end
end

final_project/app/controllers/github_controller.rb
class GithubController < ApplicationController
  def index
	if !Repository.first.nil?
		@reposits=Repository.all
	else
		myrepo
		redirect_to action: "index"
	end
  end
  private
   def myrepo
	require 'github_api'

	github = Github.new

	repos_from_github = github.repos.list(user: 'akuten1298')

	repos_from_github.each do |repo|
	  @dept=Repository.new(name: repo.name,url: repo.svn_url,stars: repo.stargazers_count)
	  @dept.save!
	end
   end

end

final_project/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
	Repository.delete_all
	Tweet.delete_all
  end
end

final_project/app/controllers/twitter_controller.rb
class TwitterController < ApplicationController
  def index
	if !Tweet.first.nil?
		@tweets=Tweet.all
	else
		mytweet
		redirect_to action: "index"
	end
  end
  private
   def mytweet
	require 'twitter'

	client = Twitter::REST::Client.new do |config|
	  config.consumer_key = "qwSTa4aFJoashomL3gAWFXMTV"
	  config.consumer_secret = "nmBA64tJcZAyc6ejzuMHCFfQDnZMyyQa4K69sUTpKLHLsQQapo"
	  config.access_token = "1188391672406667265-vH15ijJofStsWjxdBOZTtzJUALlqKr"
	  config.access_token_secret = "XAYhr5jHEtdVESeWTQD5x5E7RFFZIbD6mZisY8aLTgDs3"
	end

	timeline = client.user_timeline("freshworksinc")

	timeline.each do |tweet|
	  @tweet=Tweet.new(content: tweet.text ,retweets: tweet.retweet_count)
	  @tweet.save!
	end
   end

end

final_project/app/helpers/application_helper.rb
module ApplicationHelper
end

final_project/app/helpers/contacts_helper.rb
module ContactsHelper
end

final_project/app/helpers/github_helper.rb
module GithubHelper
end

final_project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

final_project/app/helpers/twitter_helper.rb
module TwitterHelper
end

final_project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TweetHub</title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%=root_path%>">TweetHub</a>
  <a class="nav-link" href="<%=root_path%>">Home <span class="sr-only">(current)</span></a>
  <a class="nav-link" href="<%=github_index_path%>">GitHub Repository <span class="sr-only">(current)</span></a>
  <a class="nav-link" href="<%=twitter_index_path%>">Tweets</a>
  <a class="nav-link" href="<%=contacts_index_path%>">Contacts</a>
</nav>
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}") %>
  <% end %>

  <%= yield %>
</div>

<!--<footer class="page-footer font-small bg-dark">
  <div class="footer-copyright text-center py-3 text-light">(c) 2019 Freshworks:
    <a href="https://freshworks.com"> freshworks.com</a>
  </div>
</footer>-->
</body>
</html>

final_project/app/views/twitter/index.html.erb
<div class="row">
  <div class="col-md-10">
    <h2>My Tweets</h2>
  </div>
</div>

<br/>

<ul class="list-group">
  <% @tweets.each do |tweet| %>
    <li class="list-group-item">
      <a href="#"><%= tweet.content %>     <%= tweet.retweets %></a>
    </li>
  <% end %>
</ul>